const axios = require('axios');

const API_BASE = 'http://localhost:5000/api/v1/guest';

const personas = [
    {
        businessName: 'Nova Brew Roasters',
        contactName: 'Elena Rostova',
        email: 'elena@novabrew.com',
        phone: '+1-555-0192',
        coreContext: 'We are an artisanal coffee roaster expanding into global e-commerce. We need subscription models and bulk B2B purchasing options.',
        aesthetics: 'Warm, earthy, ultra-minimalist. Lots of brown and cream tones.',
        competitors: 'Blue Bottle, Stumptown'
    },
    {
        businessName: 'VaultX Security',
        contactName: 'Marcus Chen',
        email: 'm.chen@vaultx.io',
        phone: '+1-555-8831',
        coreContext: 'Enterprise-grade penetration testing and cyber defense. We need a dark, highly technical, and imposing web presence to establish authority.',
        aesthetics: 'Dark mode exclusively. Neon blue accents, code-like typography.',
        competitors: 'CrowdStrike, FireEye'
    },
    {
        businessName: 'Lumina Sustainable Apparel',
        contactName: 'Sarah Jenkins',
        email: 'sarah@wearlumina.earth',
        phone: '+44-20-7946',
        coreContext: 'Eco-friendly fashion brand launching our summer line. Focus must be heavily on high-res photography and our carbon-neutral mission.',
        aesthetics: 'Clean white spaces, soft green accents, very editorial and airy.',
        competitors: 'Everlane, Reformation'
    },
    {
        businessName: 'Nexus AI Analytics',
        contactName: 'David Voss',
        email: 'dvoss@nexusai.tech',
        phone: '+1-555-4422',
        coreContext: 'B2B SaaS platform using predictive AI for supply chains. Our product is complex, so the website must simplify the story utilizing 3D animations and scrollytelling.',
        aesthetics: 'Modern SaaS. Purple and pink gradients, glassmorphism UI elements.',
        competitors: 'Palantir, Snowflake'
    }
];

async function simulateGuest(p) {
    try {
        console.log(`\nStarting simulation for: ${p.businessName}`);
        
        // 1. Fetch defined form from Admin settings
        const formRes = await axios.get(`${API_BASE}/form-definition`);
        const { questions, masterValues, questionOptions } = formRes.data;

        // 2. Initialize new session
        const startRes = await axios.post(`${API_BASE}/submissions`);
        const { session_id } = startRes.data;
        console.log(`[${p.businessName}] Session generated: ${session_id}`);

        // 3. Generate answers intelligently based on question text/types
        const answers = [];
        for (const q of questions) {
            let answerValue = null;

            const text = q.question_text.toLowerCase();
            
            if (q.input_type === 'text') {
                if (text.includes('business name')) answerValue = p.businessName;
                else if (text.includes('contact')) answerValue = p.contactName;
                else if (text.includes('phone')) answerValue = p.phone;
                else if (text.includes('competitor')) answerValue = p.competitors;
                else answerValue = 'Standard text input';
            } 
            else if (q.input_type === 'email') {
                answerValue = p.email;
            }
            else if (q.input_type === 'textarea') {
                if (text.includes('about')) answerValue = p.coreContext;
                else if (text.includes('design') || text.includes('aesthetic') || text.includes('feel')) answerValue = p.aesthetics;
                else answerValue = 'Generic long form description generated by automation script.';
            }
            else if (q.master_type_id) {
                // Pick a random master value belonging to this type
                const validOptions = masterValues.filter(m => m.master_type_id === q.master_type_id);
                if (validOptions.length > 0) {
                    answerValue = validOptions[Math.floor(Math.random() * validOptions.length)].value;
                } else {
                    answerValue = "other";
                }
            }
            else if (q.input_type === 'radio' || q.input_type === 'dropdown') {
                 const staticOpts = questionOptions.filter(o => o.question_id === q.id);
                 if (staticOpts.length > 0) {
                     answerValue = staticOpts[0].value;
                 } else {
                     answerValue = "yes";
                 }
            }
            else if (q.input_type === 'multiselect' || q.input_type === 'checkbox') {
                 const staticOpts = questionOptions.filter(o => o.question_id === q.id);
                 if (staticOpts.length > 0) {
                     answerValue = [staticOpts[0].value];
                 } else {
                     answerValue = ["option1"];
                 }
            } else {
                answerValue = 'Simulated Data';
            }

            answers.push({ question_id: q.id, answer_value: answerValue });
        }

        // 4. Submit Answers
        await axios.put(`${API_BASE}/submissions/${session_id}/answers`, { answers });
        console.log(`[${p.businessName}] Answers payload submitted.`);

        // 5. Complete Submission
        await axios.post(`${API_BASE}/submissions/${session_id}/complete`, {
            contact_email: p.email,
            contact_phone: p.phone,
            business_name: p.businessName
        });
        console.log(`[${p.businessName}] Completion workflow finalized.`);
        
    } catch (err) {
        console.error(`Error simulating ${p.businessName}:`, err.message);
    }
}

async function run() {
    console.log('Initiating highly creative organic Guest Simulation Sequence...');
    for (const p of personas) {
        await simulateGuest(p);
    }
    console.log('\nAll 4 organic projects successfully injected via HTTP API layers!');
}

run();
